name             'nateApp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures nateApp'
long_description 'Installs/Configures nateApp'
version          '0.1.0'

depends          'ntp'
depends          'mysql'
depends          'apache2'
depends          'php'
depends          'haproxy'
depends		 'apt'

supports 'ubuntu'
